name: flutter_azlir
description: A Very Good App
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'

dependencies:
  animations: ^2.0.11
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dartx: ^1.2.0
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.5.1
  flutter_widget_from_html: ^0.15.2
  font_awesome_flutter: ^10.7.0
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  hive_ce: ^2.4.4
  hive_ce_flutter: ^2.1.0
  icons_launcher: ^3.0.0
  injectable: ^2.3.2
  intl: ^0.19.0
  loader_overlay: ^4.0.0
  material_symbols_icons: ^4.2719.3
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.2
  pausable_timer: ^3.1.0+3
  photo_view: ^0.15.0
  responsive_builder: ^0.7.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: any
  custom_lint: any
  dependency_validator: ^4.1.0
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  riverpod_generator: ^2.4.0
  riverpod_lint: any
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  generate: true
